var charizardHP = 9000
var charizardNum = 10
var charizardType = "water and ice"
var charizardBestMove = "splash"
var charizardLastEvo = true
var charizardAttack = 5
var charizardDefense = 5000
var charizardSpeed = 10000000
var charizardSpecialAttack = 13
var charizardSpecialDefense = 113
